name: Verify available python versions

on:
 push:
   branches: [main]
 pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          python-version: ['2.7', '3.5', '3.6', '3.7', '3.8']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
